### ISSUE TITLE
Rename "master" branches to "main"

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard-maintenance-scripts#158]
Github is pushing for the name "master" to retire, replacing it with "main". Since October 1st, unless configured otherwise, all new repositories have their main branch named "main".

What's OCP strategy gonna be?

- use "main" everywhere?
- only use "main" on new repos?
- keep "master"?
- use something else such as "first", "best", "root", "god", "1", "0", "prod"? :trollface:

**Comment by jpmckinney** [comment]
We serve extensions from GitHub at URLs that contain "master". According to https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/, if we delete `master` and set `main` as default, these URLs will redirect.

* [ ] Add redirects from master to main for profiles, e.g. https://standard.open-contracting.org/profiles/eu/master/en/
* [ ] Add redirects from master to main in Extension Explorer
* [ ] Rename extension resources in Transifex
* [ ] Update `deploy` repo (it deploys the `master` branch, and otherwise mentions `master` a lot)
* [ ] Update `raw.githubusercontent.com` URLs pointing to `master` across all repositories
* [ ] Update `github.com/open-contracting` URLs pointing to `master` across all repositories
* [ ] Go through each repository and fix miscellaneous occurrences
* [ ] Check that ReadTheDocs automatically builds the default branch (none of them explicitly set *Default branch* under *Advanced Settings* to "master" so this should work)

It looks like to changes will be difficult, just long.

**Comment by jpmckinney** [comment]
To do later, once Young Innovations delivers the project:

* [ ] covid-19-procurement-explorer-admin
* [ ] covid-19-procurement-explorer-public

**Comment by jpmckinney** [comment]
Some false positives in comments:

* https://github.com/twbs/bootstrap/blob

**Comment by ColinMaudry** [comment]
Is there something to do on client side (typically, the cloned repos on my laptop)?

**Comment by ColinMaudry** [comment]
Also, are the extension repositories going to be impacted? https://github.com/open-contracting-extensions

60 repos!

**Comment by jpmckinney** [comment]
> Also, are the extension repositories going to be impacted? https://github.com/open-contracting-extensions

No, there is too much logic that depends on extension repos using "master" as the live branch, so they will not be changed. I updated this comment: https://github.com/open-contracting/standard-maintenance-scripts/issues/158#issuecomment-729805445

**Comment by jpmckinney** [comment]
> Is there something to do on client side (typically, the cloned repos on my laptop)?

For the standard, extensions and `standard_extension_template`, they haven't changed.

For other repositories, GitHub shares instructions if you visit the repo's page. I'll share them below.

For profiles and `standard_profile_template`, the default branch is now `latest`. You must do:

```
git branch -m master latest
git fetch origin
git branch -u origin/latest latest
```

For all other repositories (code repositories), you must do:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
